-- ========================================
-- 修复数据库表字段注释的中文乱码问题
-- ========================================

USE logistics_system;

-- 1. 修复 users 表字段注释
ALTER TABLE users MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '用户ID';
ALTER TABLE users MODIFY COLUMN username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名';
ALTER TABLE users MODIFY COLUMN real_name VARCHAR(50) COMMENT '真实姓名';
ALTER TABLE users MODIFY COLUMN password VARCHAR(255) COMMENT '密码（BCrypt加密）';
ALTER TABLE users MODIFY COLUMN email VARCHAR(100) COMMENT '邮箱';
ALTER TABLE users MODIFY COLUMN phone VARCHAR(20) COMMENT '电话号码';
ALTER TABLE users MODIFY COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '角色：ADMIN, USER';
ALTER TABLE users MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '状态：1-启用，0-禁用';
ALTER TABLE users MODIFY COLUMN avatar VARCHAR(255) COMMENT '头像URL';
ALTER TABLE users MODIFY COLUMN last_login_time DATETIME COMMENT '最后登录时间';
ALTER TABLE users MODIFY COLUMN last_login_ip VARCHAR(50) COMMENT '最后登录IP';
ALTER TABLE users MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE users MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE users MODIFY COLUMN deleted_at DATETIME COMMENT '软删除时间';
ALTER TABLE users MODIFY COLUMN ding_union_id VARCHAR(100) COMMENT '钉钉unionId（跨企业唯一标识）';
ALTER TABLE users MODIFY COLUMN ding_user_id VARCHAR(100) COMMENT '钉钉userId（企业内唯一标识）';
ALTER TABLE users MODIFY COLUMN corp_id VARCHAR(100) COMMENT '企业CorpId';
ALTER TABLE users MODIFY COLUMN login_source VARCHAR(20) DEFAULT 'PASSWORD' COMMENT '登录来源：PASSWORD, DINGTALK';

-- 2. 修复 allowed_corp_ids 表字段注释
ALTER TABLE allowed_corp_ids MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT 'ID';
ALTER TABLE allowed_corp_ids MODIFY COLUMN corp_id VARCHAR(100) NOT NULL UNIQUE COMMENT '企业CorpId';
ALTER TABLE allowed_corp_ids MODIFY COLUMN corp_name VARCHAR(200) COMMENT '企业名称';
ALTER TABLE allowed_corp_ids MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '状态：1-启用，0-禁用';
ALTER TABLE allowed_corp_ids MODIFY COLUMN created_by VARCHAR(50) COMMENT '创建人';
ALTER TABLE allowed_corp_ids MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE allowed_corp_ids MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE allowed_corp_ids MODIFY COLUMN deleted_at DATETIME COMMENT '软删除时间';

-- 3. 修复 shops 表字段注释
ALTER TABLE shops MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '商店ID';
ALTER TABLE shops MODIFY COLUMN shop_domain VARCHAR(255) NOT NULL UNIQUE COMMENT 'Shopify店铺域名';
ALTER TABLE shops MODIFY COLUMN shop_name VARCHAR(255) COMMENT '店铺名称';
ALTER TABLE shops MODIFY COLUMN access_token TEXT COMMENT 'Shopify访问令牌';
ALTER TABLE shops MODIFY COLUMN scope TEXT COMMENT '授权范围';
ALTER TABLE shops MODIFY COLUMN is_active TINYINT DEFAULT 1 COMMENT '是否激活：1-是，0-否';
ALTER TABLE shops MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE shops MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 4. 修复 orders 表字段注释
ALTER TABLE orders MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '订单ID';
ALTER TABLE orders MODIFY COLUMN shop_id BIGINT NOT NULL COMMENT '关联的店铺ID';
ALTER TABLE orders MODIFY COLUMN shopify_order_id BIGINT NOT NULL COMMENT 'Shopify订单ID';
ALTER TABLE orders MODIFY COLUMN order_number VARCHAR(50) COMMENT '订单编号';
ALTER TABLE orders MODIFY COLUMN customer_email VARCHAR(255) COMMENT '客户邮箱';
ALTER TABLE orders MODIFY COLUMN customer_name VARCHAR(255) COMMENT '客户姓名';
ALTER TABLE orders MODIFY COLUMN total_price DECIMAL(10,2) COMMENT '订单总价';
ALTER TABLE orders MODIFY COLUMN currency VARCHAR(10) COMMENT '货币类型';
ALTER TABLE orders MODIFY COLUMN financial_status VARCHAR(50) COMMENT '财务状态';
ALTER TABLE orders MODIFY COLUMN fulfillment_status VARCHAR(50) COMMENT '物流状态';
ALTER TABLE orders MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE orders MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 5. 修复 order_items 表字段注释
ALTER TABLE order_items MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '订单项ID';
ALTER TABLE order_items MODIFY COLUMN order_id BIGINT NOT NULL COMMENT '关联的订单ID';
ALTER TABLE order_items MODIFY COLUMN product_id BIGINT COMMENT '产品ID';
ALTER TABLE order_items MODIFY COLUMN variant_id BIGINT COMMENT '变体ID';
ALTER TABLE order_items MODIFY COLUMN title VARCHAR(255) COMMENT '产品标题';
ALTER TABLE order_items MODIFY COLUMN quantity INT COMMENT '数量';
ALTER TABLE order_items MODIFY COLUMN price DECIMAL(10,2) COMMENT '单价';
ALTER TABLE order_items MODIFY COLUMN sku VARCHAR(100) COMMENT 'SKU';

-- 6. 修复 tracking_numbers 表字段注释
ALTER TABLE tracking_numbers MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '物流编号ID';
ALTER TABLE tracking_numbers MODIFY COLUMN order_id BIGINT COMMENT '关联的订单ID';
ALTER TABLE tracking_numbers MODIFY COLUMN fulfillment_id BIGINT COMMENT '关联的履行ID';
ALTER TABLE tracking_numbers MODIFY COLUMN tracking_number VARCHAR(255) NOT NULL COMMENT '物流追踪号';
ALTER TABLE tracking_numbers MODIFY COLUMN carrier_code VARCHAR(50) COMMENT '物流公司代码';
ALTER TABLE tracking_numbers MODIFY COLUMN carrier_name VARCHAR(255) COMMENT '物流公司名称';
ALTER TABLE tracking_numbers MODIFY COLUMN status VARCHAR(50) COMMENT '物流状态';
ALTER TABLE tracking_numbers MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE tracking_numbers MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 7. 修复 tracking_events 表字段注释
ALTER TABLE tracking_events MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '物流事件ID';
ALTER TABLE tracking_events MODIFY COLUMN tracking_id BIGINT NOT NULL COMMENT '关联的物流追踪ID';
ALTER TABLE tracking_events MODIFY COLUMN event_time DATETIME COMMENT '事件时间';
ALTER TABLE tracking_events MODIFY COLUMN location VARCHAR(255) COMMENT '地点';
ALTER TABLE tracking_events MODIFY COLUMN status VARCHAR(100) COMMENT '状态';
ALTER TABLE tracking_events MODIFY COLUMN description TEXT COMMENT '描述信息';
ALTER TABLE tracking_events MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- 8. 修复 webhook_logs 表字段注释
ALTER TABLE webhook_logs MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT 'Webhook日志ID';
ALTER TABLE webhook_logs MODIFY COLUMN shop_id BIGINT COMMENT '关联的店铺ID';
ALTER TABLE webhook_logs MODIFY COLUMN topic VARCHAR(100) COMMENT 'Webhook主题';
ALTER TABLE webhook_logs MODIFY COLUMN payload TEXT COMMENT '载荷数据';
ALTER TABLE webhook_logs MODIFY COLUMN headers TEXT COMMENT 'HTTP头信息';
ALTER TABLE webhook_logs MODIFY COLUMN status VARCHAR(20) COMMENT '处理状态：SUCCESS, FAILED';
ALTER TABLE webhook_logs MODIFY COLUMN error_message TEXT COMMENT '错误信息';
ALTER TABLE webhook_logs MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

SELECT '所有表字段注释已更新完成!' as message;
